title __DELFINEN's Class Diagram__\n



  Controllere.FormandController o-- Handler.FormandHandler : formandHandler
  Controllere.FormandController o-- UI.FormandMenu : formandMenu
  Controllere.KassererController o-- Handler.KassererHandler : kassererHandler
  Controllere.KassererController o-- UI.KassererMenu : kassererMenu
  Controllere.MainController o-- UserLogin.FormandLogin : formandLogin
  Controllere.MainController o-- UserLogin.KassererLogin : kassererLogin
  Controllere.MainController o-- UserLogin.TraenerLogin : traenerLogin
  Controllere.TraenerController o-- Handler.TraenerHandler : traenerHandler
  Controllere.TraenerController o-- UI.TraenerMenu : traenerMenu
  Data.ImportData o-- Domain.Medlem : medlem
  Data.ImportData o-- Domain.Resultater : resultater
  Domain.Resultater .up.|> java.lang.Comparable
  Handler.FormandHandler o-- Data.ExportData : exportData
  Handler.FormandHandler o-- Data.ImportData : importData
  Handler.KassererHandler o-- Data.ImportData : importData
  Handler.TraenerHandler o-- UI.TraenerMenu : traenerMenu
  UI.FormandMenu .up.|> UI.UI
  UI.KassererMenu .up.|> UI.UI
  UI.TraenerMenu .up.|> UI.UI
  UserLogin.FormandLogin .up.|> UserLogin.Login
  UserLogin.FormandLogin o-- Controllere.FormandController : formandController
  UserLogin.KassererLogin .up.|> UserLogin.Login
  UserLogin.KassererLogin o-- Controllere.KassererController : kassererController
  UserLogin.TraenerLogin .up.|> UserLogin.Login
  UserLogin.TraenerLogin o-- Controllere.TraenerController : traenerController


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml